[package]
name = "obws"
version = "0.11.5"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
rust-version = "1.68"
license = "MIT"
readme = "README.md"
description = "The obws (obvious) remote control library for OBS."
homepage = "https://github.com/dnaka91/obws"
repository = "https://github.com/dnaka91/obws"
categories = ["api-bindings", "web-programming"]
keywords = ["async", "obs", "obs-websocket", "remote-control", "tokio"]
include = ["examples/**/*", "tests/**/*", "src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[package.metadata.docs.rs]
features = ["events", "tls"]

[dependencies]
async-stream = { version = "0.3.5", optional = true }
base64 = "0.21.7"
bitflags = { version = "2.4.2", features = ["serde"] }
futures-util = { version = "0.3.30", features = ["sink"] }
rgb = { version = "0.8.37", default-features = false }
semver = { version = "1.0.21", features = ["serde"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
serde_repr = "0.1.18"
serde_with = "3.4.0"
sha2 = "0.10.8"
thiserror = "1.0.56"
time = "0.3.31"
tokio = { version = "1.35.1", features = ["net", "rt", "sync", "time"] }
tokio-tungstenite = "0.21.0"
tracing = "0.1.40"

[dev-dependencies]
anyhow = "1.0.79"
dotenvy = "0.15.7"
serde_test = "1.0.176"
tokio = { version = "1.35.1", features = ["fs", "macros", "rt-multi-thread", "time"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[features]
default = []
test-integration = []
events = ["dep:async-stream"]
tls = ["tokio-tungstenite/rustls-tls-webpki-roots"]

[[example]]
name = "events"
required-features = ["events"]

[[test]]
name = "integration"
required-features = ["events"]
