[package]
name = "obws"
version = "0.8.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
resolver = "2"
license = "MIT"
readme = "README.md"
description = "The obws (obvious) remote control library for OBS."
homepage = "https://github.com/dnaka91/obws"
repository = "https://github.com/dnaka91/obws"
categories = ["api-bindings", "web-programming"]
keywords = ["async", "obs", "obs-websocket", "remote-control", "tokio"]
include = ["examples/**/*", "tests/**/*", "src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[package.metadata.docs.rs]
features = ["events", "tls"]

[dependencies]
async-stream = { version = "0.3.2", optional = true }
base64 = "0.13.0"
bitflags = "1.2.1"
chrono = { version = "0.4.19", features = ["serde"] }
futures-util = { version = "0.3.15", features = ["sink"] }
log = "0.4.14"
semver = { version = "1.0.3", features = ["serde"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde_repr = "0.1.7"
serde_with = "1.9.4"
sha2 = "0.9.5"
thiserror = "1.0.26"
tokio = { version = "1.8.2", features = ["net", "rt", "sync"] }
tokio-tungstenite = "0.14.0"

[dev-dependencies]
anyhow = "1.0.42"
dotenv = "0.15.0"
pretty_env_logger = "0.4.0"
serde_test = "1.0.126"
tokio = { version = "1.8.2", features = ["fs", "macros", "rt-multi-thread", "time"] }

[features]
default = []
test-integration = []
events = ["async-stream"]
tls = ["tokio-tungstenite/rustls-tls"]

[[example]]
name = "events"
required-features = ["events"]

[[test]]
name = "general"
required-features = ["events"]
