[package]
name = "obws"
version = "0.10.0-beta.3"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
rust-version = "1.61"
license = "MIT"
readme = "README.md"
description = "The obws (obvious) remote control library for OBS."
homepage = "https://github.com/dnaka91/obws"
repository = "https://github.com/dnaka91/obws"
categories = ["api-bindings", "web-programming"]
keywords = ["async", "obs", "obs-websocket", "remote-control", "tokio"]
include = ["examples/**/*", "tests/**/*", "src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[package.metadata.docs.rs]
features = ["events", "tls"]

[dependencies]
async-stream = { version = "0.3.3", optional = true }
base64 = "0.13.0"
bitflags = "1.3.2"
futures-util = { version = "0.3.24", features = ["sink"] }
rgb = { version = "0.8.33", default-features = false }
semver = { version = "1.0.13", features = ["serde"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
serde_repr = "0.1.9"
serde_with = "2.0.0"
sha2 = "0.10.5"
thiserror = "1.0.33"
time = "0.3.14"
tokio = { version = "1.21.0", features = ["net", "rt", "sync", "time"] }
tokio-tungstenite = "0.17.2"
tracing = "0.1.36"

[dev-dependencies]
anyhow = "1.0.63"
dotenvy = "0.15.3"
serde_test = "1.0.144"
tokio = { version = "1.21.0", features = ["fs", "macros", "rt-multi-thread", "time"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }

[features]
default = []
test-integration = []
events = ["async-stream"]
tls = ["tokio-tungstenite/rustls-tls-webpki-roots"]

[[example]]
name = "events"
required-features = ["events"]

[[test]]
name = "integration"
required-features = ["events"]
