[package]
name = "obws"
version = "0.8.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
rust-version = "1.56"
license = "MIT"
readme = "README.md"
description = "The obws (obvious) remote control library for OBS."
homepage = "https://github.com/dnaka91/obws"
repository = "https://github.com/dnaka91/obws"
categories = ["api-bindings", "web-programming"]
keywords = ["async", "obs", "obs-websocket", "remote-control", "tokio"]
include = ["examples/**/*", "tests/**/*", "src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[package.metadata.docs.rs]
features = ["events", "tls"]

[dependencies]
async-stream = { version = "0.3.3", optional = true }
base64 = "0.13.0"
bitflags = "1.3.2"
futures-util = { version = "0.3.21", features = ["sink"] }
semver = { version = "1.0.7", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_repr = "0.1.7"
serde_with = "1.12.1"
sha2 = "0.10.2"
thiserror = "1.0.30"
time = "0.3.9"
tokio = { version = "1.17.0", features = ["net", "rt", "sync"] }
tokio-tungstenite = "0.17.1"
tracing = "0.1.32"

[dev-dependencies]
anyhow = "1.0.56"
dotenv = "0.15.0"
serde_test = "1.0.136"
tokio = { version = "1.17.0", features = ["fs", "macros", "rt-multi-thread", "time"] }
tracing-subscriber = { version = "0.3.10", features = ["env-filter"] }

[features]
default = []
test-integration = []
events = ["async-stream"]
tls = ["tokio-tungstenite/rustls-tls-webpki-roots"]

[[example]]
name = "events"
required-features = ["events"]

[[test]]
name = "integration"
required-features = ["events"]
