[licenses]
allow = [
    "MPL-2.0",
    "OpenSSL",
]
allow-osi-fsf-free = "both"

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
name = "unicode-ident"
version = "*"

[bans]
skip = [
    { name = "base64", version = "=0.13.1" },
]
