[licenses]
allow = [
    "MPL-2.0",
    "OpenSSL",
]
allow-osi-fsf-free = "both"

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "block-buffer", version = "=0.9.0" },
    { name = "digest", version = "0.9.0" },
]
